#!/usr/bin/env python3
"""Print Rust verification-key constants for the Solana groth16-verifier program.

Encoding matches the EVM pairing precompile convention the program mirrors:
  G1 = be32(x) || be32(y)
  G2 = be32(x_c1) || be32(x_c0) || be32(y_c1) || be32(y_c0)   (imaginary first)

snarkjs verification_key.json stores G2 as [[c0, c1], ...], hence the swap.

Usage:
  python3 scripts/export_solana_vk.py test/fixtures/v2/verification_key.json V2
"""

import json
import sys


def be32(dec: str) -> bytes:
    return int(dec).to_bytes(32, "big")


def fmt(data: bytes, indent: str = "    ") -> str:
    lines = []
    for off in range(0, len(data), 16):
        chunk = data[off : off + 16]
        lines.append(indent + " ".join(f"0x{b:02x}," for b in chunk))
    return "\n".join(lines)


def g1(p) -> bytes:
    return be32(p[0]) + be32(p[1])


def g2(p) -> bytes:
    return be32(p[0][1]) + be32(p[0][0]) + be32(p[1][1]) + be32(p[1][0])


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    vk = json.load(open(sys.argv[1]))
    suffix = sys.argv[2].upper()

    print(f"// Generated by circuits/scripts/export_solana_vk.py from {sys.argv[1]}")
    print(f"const VK_ALPHA_{suffix}: [u8; 64] = [")
    print(fmt(g1(vk["vk_alpha_1"])))
    print("];\n")
    for name, key in (("BETA", "vk_beta_2"), ("GAMMA", "vk_gamma_2"), ("DELTA", "vk_delta_2")):
        print(f"const VK_{name}_{suffix}: [u8; 128] = [")
        print(fmt(g2(vk[key])))
        print("];\n")
    n = len(vk["IC"])
    print(f"const VK_IC_{suffix}: [[u8; 64]; {n}] = [")
    for i, p in enumerate(vk["IC"]):
        print(f"    // IC{i}")
        print("    [")
        print(fmt(g1(p), indent="        "))
        print("    ],")
    print("];")


if __name__ == "__main__":
    main()
